In [1]:
import numpy as np

# 1.Basic

In [2]:
array = np.ones((2,3,4))
print('Shape:',array.shape)
print()
print(array)

Shape: (2, 3, 4)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
array_0 = np.mean(array, axis=0)
print('All elements in Axis=0 would disappear!')
print('Shape:', array_0.shape)
print()
print(array_0)

All elements in Axis=0 would disappear!
Shape: (3, 4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
array_1 = np.mean(array, axis=1)
print('All elements in Axis=1 would disappear!')
print('Shape:', array_1.shape)
print()
print(array_1)

All elements in Axis=1 would disappear!
Shape: (2, 4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
array_01 = np.mean(array, axis=(0,1))
print('All elements in Axis=0 and Axis=1 would disappear!')
print('Shape:', array_01.shape)
print()
print(array_01)

All elements in Axis=0 and Axis=1 would disappear!
Shape: (4,)

[1. 1. 1. 1.]


In [6]:
array_2 = np.mean(array, axis=2)
print('All elements in Axis=2 would disappear!')
print('Shape:', array_2.shape)
print()
print(array_2)

All elements in Axis=2 would disappear!
Shape: (2, 3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
array_012 = np.mean(array, axis=(0,1,2))
print('All elements in Axis=0, Axis=1 and Axis=2 would disappear!')
print('Shape:', array_012.shape)
print()
print(array_012)

All elements in Axis=0, Axis=1 and Axis=2 would disappear!
Shape: ()

1.0


# 2. Advanced

In [8]:
x = np.array([[[7, 1, 2, 3],
               [4, 8, 3, 1],
               [2, 3, 7, 5]],
              [[7, 3, 2, 3],
               [6, 1, 1, 3],
               [8, 2, 8, 0]]])
print(x)
print(x.shape)

[[[7 1 2 3]
  [4 8 3 1]
  [2 3 7 5]]

 [[7 3 2 3]
  [6 1 1 3]
  [8 2 8 0]]]
(2, 3, 4)


In [9]:
np.set_printoptions(precision=1)

In [10]:
x_0 = np.mean(x, axis=0)
print('axis=0')
print(x_0)
print(x_0.shape)

axis=0
[[7.  2.  2.  3. ]
 [5.  4.5 2.  2. ]
 [5.  2.5 7.5 2.5]]
(3, 4)


In [11]:
x_1 = np.mean(x, axis=1)
print('axis=1')
print(x_1)
print(x_1)

axis=1
[[4.3 4.  4.  3. ]
 [7.  2.  3.7 2. ]]
[[4.3 4.  4.  3. ]
 [7.  2.  3.7 2. ]]


In [12]:
x_2 = np.mean(x, axis=2)
print('axis=2')
print(x_2)
print(x_2.shape)

axis=2
[[3.2 4.  4.2]
 [3.8 2.8 4.5]]
(2, 3)


In [13]:
new_x = np.mean(x, axis=(0, 1))
print('axis=0 & axis=1')
print(new_x)
print(new_x.shape)

axis=0 & axis=1
[5.7 3.  3.8 2.5]
(4,)


In [14]:
new = np.mean(x, axis=(0, 1, 2))
print('axis=0 & axis=1 & axis=2')
print(new)
print(new.shape)

axis=0 & axis=1 & axis=2
3.75
()
